CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY,
  first VARCHAR NOT NULL,
  last VARCHAR NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

---- create above / drop below ----

DROP TABLE IF EXISTS users;
